#[path = "google.protobuf.rs"]
pub mod google_protobuf;
#[path = "lib_manual.rs"]
pub mod lib_manual;
#[path = "ydb.coordination.rs"]
pub mod ydb_coordination;
#[path = "ydb.coordination.v1.rs"]
pub mod ydb_coordination_v1;
#[path = "ydb.discovery.rs"]

pub mod ydb_discovery;
#[path = "ydb.discovery.v1.rs"]
pub mod ydb_discovery_v1;
#[path = "ydb.experimental.rs"]
pub mod ydb_experimental;
#[path = "ydb.experimental.v1.rs"]
pub mod ydb_experimental_v1;
#[path = "ydb.export.rs"]
pub mod ydb_export;
#[path = "ydb.export.v1.rs"]
pub mod ydb_export_v1;
#[path = "ydb.import.rs"]
pub mod ydb_import;
#[path = "ydb.import.v1.rs"]
pub mod ydb_import_v1;
#[path = "ydb.issue.rs"]
pub mod ydb_issue;
#[path = "ydb.monitoring.rs"]
pub mod ydb_monitoring;
#[path = "ydb.monitoring.v1.rs"]
pub mod ydb_monitoring_v1;
#[path = "ydb.operation.v1.rs"]
pub mod ydb_operation_v1;
#[path = "ydb.operations.rs"]
pub mod ydb_operations;
#[path = "ydb.pers_queue.cluster_discovery.rs"]
pub mod ydb_pers_queue_cluster_discovery;
#[path = "ydb.pers_queue.error_code.rs"]
pub mod ydb_pers_queue_error_code;
#[path = "ydb.pers_queue.v1.rs"]
pub mod ydb_pers_queue_v1;
#[path = "ydb.rate_limiter.rs"]
pub mod ydb_rate_limiter;
#[path = "ydb.rate_limiter.v1.rs"]
pub mod ydb_rate_limiter_v1;
#[path = "ydb.rs"]
pub mod ydb;
#[path = "ydb.scheme.rs"]
pub mod ydb_scheme;
#[path = "ydb.scheme.v1.rs"]
pub mod ydb_scheme_v1;
#[path = "ydb.scripting.rs"]
pub mod ydb_scripting;
#[path = "ydb.scripting.v1.rs"]
pub mod ydb_scripting_v1;
#[path = "ydb.table.rs"]
pub mod ydb_table;
#[path = "ydb.table.v1.rs"]
pub mod ydb_table_v1;
#[path = "ydb.table_stats.rs"]
pub mod ydb_table_stats;
