[package]
publish=false
version="0.0.0"
name = "ydb-grpc-helpers"
authors = ["rekby <timofey.koolin@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]

[dependencies]
