name: publish rust crate
on:
  workflow_dispatch:
    inputs:
      crate:
        description: Select crate to publish
        required: true
        type: choice
        options:
          - sdk
          - ydb-grpc
      version:
        description: "Version of crate, numbers only. Example: 0.0.1"
        required: true
        type: string

jobs:
  testSecretAvailable:
    runs-on: ubuntu-latest
    env:
      CARGO_REGISTRY_TOKEN: ${{ secrets.CARGO_REGISTRY_TOKEN }}
    steps:
      - run: |
          echo PUBLISH: "${{ github.event.inputs.crate }}"
          echo VERSION: "${{ github.event.inputs.version }}"
          sleep 10
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: bash scripts/publish-crate.sh "${{ github.event.inputs.crate }}" "${{ github.event.inputs.version }}"
