name: publish rust crate
on: workflow_dispatch
jobs:
  testSecretAvailable:
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
    steps:
      - run: |
          [ -z "$TEST_SECRET" ] && echo empty || echo detected
