name: publish rust crate
on:
  workflow_dispatch:
    inputs:
      crate:
        description: Select crate to publish
        required: true
        type: choice
        options:
          - grpc-generated
          - sdk
      version:
        description: "Version of crate, numbers only. Example: 0.0.1"
        required: true
        type: string

jobs:
  testSecretAvailable:
    runs-on: ubuntu-latest
    env:
      TEST_SECRET: ${{ secrets.TEST_SECRET }}
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - run: |
          [ -z "$TEST_SECRET" ] && echo empty || echo detected
          echo crate: ${{ github.event.inputs.crate }}:${{github.event.inputs.version}}
          pwd
          ls -la
