name: Linter

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

permissions:
  contents: read

env:
  CARGO_TERM_COLOR: always
  CARGO_REGISTRIES_CRATES_IO_PROTOCOL: sparse
  RUST_VERSION_NEW: "1.91.0"

jobs:
  check-code-style:
    strategy:
      fail-fast: false
      matrix:
        rust_version: [ "RUST_VERSION_NEW" ]

    runs-on: ubuntu-24.04

    steps:
    - name: Checkout
      uses: actions/checkout@v4
      with:
        submodules: true

    - name: Install rust
      uses: dtolnay/rust-toolchain@v1
      with:
        toolchain: ${{ env[matrix.rust_version] }}
        components: clippy, rustfmt

    - name: Install taplo
      uses: uncenter/setup-taplo@v2
      with:
          version: "0.10.0"

    - name: Rust version
      id: rust_version_step
      run: |
        rustc --version
        cargo --version
        echo "CARGO_INCREMENTAL=$CARGO_INCREMENTAL"
        echo "::set-output name=version::$(rustc --version | cut -d ' ' -f 2)"

    - name: Rust cache
      uses: Swatinem/rust-cache@v2

    - name: Rustfmt check
      run: | 
        cargo fmt --all --check

    - name: Clippy check
      run: |
        cargo clippy --workspace --all-targets --no-deps --exclude=ydb-grpc -- -D warnings

    - name: Taplo check
      run: |
          taplo fmt --check
          git diff --exit-code

  check-grpc-build:
    strategy:
      fail-fast: false
      matrix:
        rust_version: [ "RUST_VERSION_NEW" ]

    runs-on: ubuntu-24.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
            submodules: true

      - name: Install protoc
        uses: arduino/setup-protoc@v3
        with:
          version: "33.2"

      - name: Install rust
        uses: dtolnay/rust-toolchain@v1
        with:
          toolchain: ${{ env[matrix.rust_version] }}

      - name: Rust version
        id: rust_version_step
        run: |
          rustc --version
          cargo --version
          echo "CARGO_INCREMENTAL=$CARGO_INCREMENTAL"
          echo "::set-output name=version::$(rustc --version | cut -d ' ' -f 2)"

      - name: Build tonic-grpc
        run: |
          cargo build -p ydb-grpc --features regenerate-sources
          git diff --exit-code

